name: "Build Artifacts"
on:
  push:

permissions:
  contents: write
  repository-projects: write
  actions: write
  statuses: read

jobs:
  release:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Wait Tests
        id: test_result
        uses: Sibz/await-status-action@v1
        with:
          contexts: test-status
          authToken: ${{ secrets.GITHUB_TOKEN }}
          timeout: 30

      - name: Check Test Result
        if: steps.test_result.outputs.result != 'success'
        run: |
          echo "failed ${{ steps.test_result.outputs.failedCheckNames }}"
          echo "status ${{ steps.test_result.outputs.failedCheckStates }}"
          exit 1

      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Set OS-specific vars
        id: vars
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            echo "extension=.exe" >> $GITHUB_OUTPUT
            echo "GOOS=windows" >> $GITHUB_OUTPUT
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            echo "extension=" >> $GITHUB_OUTPUT
            echo "GOOS=linux" >> $GITHUB_OUTPUT
          else
            echo "extension=" >> $GITHUB_OUTPUT
            echo "GOOS=darwin" >> $GITHUB_OUTPUT
          fi

      - name: Build AMD64
        run: |
          GOOS=${{ steps.vars.outputs.GOOS }} GOARCH=amd64 go build -ldflags="-s -w" -trimpath -o pummit-${{ steps.vars.outputs.GOOS }}-amd64${{ steps.vars.outputs.extension }} ./cmd/pummit
        shell: bash

      - name: Build ARM64
        run: |
          GOOS=${{ steps.vars.outputs.GOOS }} GOARCH=arm64 go build -ldflags="-s -w" -trimpath -o pummit-${{ steps.vars.outputs.GOOS }}-arm64${{ steps.vars.outputs.extension }} ./cmd/pummit
        shell: bash

      - name: Upload AMD64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pummit_${{ steps.vars.outputs.GOOS }}_amd64
          path: pummit-${{ steps.vars.outputs.GOOS }}-amd64${{ steps.vars.outputs.extension }}
          retention-days: 7

      - name: Upload ARM64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pummit_${{ steps.vars.outputs.GOOS }}_arm64
          path: pummit-${{ steps.vars.outputs.GOOS }}-arm64${{ steps.vars.outputs.extension }}
          retention-days: 7
