name: delete branch on close pr
on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  repository-projects: write

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: delete branch
        uses: SvanBoxel/delete-merged-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
