name: Release
on:
  release:
    types:
      - published

permissions:
  contents: write
  repository-projects: write
  actions: write
  statuses: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    # Multi platform support
    # strategy:
    # matrix:
    # platform: [macos-latest, ubuntu-latest, windows-latest]
    # fail-fast: false

    # runs-on: ${{ matrix.platform }}

    steps:
      - name: Wait Tests
        id: test_result
        uses: Sibz/await-status-action@v1.0.1
        with:
          contexts: test-status
          authToken: ${{ secrets.GITHUB_TOKEN }}
          timeout: 30
      - name: Check Test Result
        if: steps.test_result.outputs.result != 'success'
        run: |
          echo "feiled ${{ steps.test_result.outputs.failedCheckNames }}"
          echo "status ${{ steps.test_result.outputs.failedCheckStates }}"
          exit 1
      - name: Checkout Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Release
        uses: goreleaser/goreleaser-action@v5
        env:
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: release --rm-dist
