name: Test CLI

on:
  push:

permissions:
  statuses: write

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Test
        id: test_step
        continue-on-error: true
        run: go build -ldflags="-s -w" -trimpath src/main.go

      - name: Set Check Status Success
        uses: Sibz/github-status-action@v1
        if: steps.test_step.outcome == 'success'
        with:
          context: test-status
          authToken: ${{ secrets.GITHUB_TOKEN }}
          state: success
      - name: Set Check Status Failure
        uses: Sibz/github-status-action@v1
        if: steps.test_step.outcome == 'failure'
        with:
          context: test-status
          authToken: ${{ secrets.GITHUB_TOKEN }}
          state: failure

      - name: Fail
        uses: Sibz/action-always-fail@v1.0.1
        if: steps.test_step.outcome == 'failure'
