name: Translate README

on:
  push:
    branches:
      - develop
    paths:
      - ".github/workflows/translate-readme.yml"
      - "README.md"

permissions:
  contents: write
  repository-projects: write

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # ISO Langusge Codes: https://cloud.google.com/translate/docs/languages
      - name: Adding README - Chinese Simplified
        uses: dephraiim/translate-readme@main
        with:
          LANG: zh-CN
      - name: Adding README - Chinese Traditional
        uses: dephraiim/translate-readme@main
        with:
          LANG: zh-TW
      - name: Adding README - English
        uses: dephraiim/translate-readme@main
        with:
          LANG: en
      - name: Adding README - Hangle
        uses: dephraiim/translate-readme@main
        with:
          LANG: ko
